### PR TITLE
fixes text rotation

### LINKED ISSUE #83: labels are misaligned when rotating shapes
### Expected Behavior
When rotating a shape, the labels should rotate with it.

### Current Behavior
Currently, as a shape rotates away from 0, the vertical alignment of the label becomes misaligned. Here is the code inside of `Shape.js` which sets the label rotation: https://github.com/d3plus/d3plus-shape/blob/master/src/Shape/Shape.js#L435-L439

This might actually be an issue with `d3plus-text`, so maybe test it there if you're hitting a brick wall.

### Steps to Reproduce (for bugs)
https://jsfiddle.net/nfd9bo8q/54/

### PR DESCRIPTION
**Pull request by cnavarreteliz**
(closes d3plus/d3plus-shape#83)

### Description

This bug was caused when rotation angle was different to zero. 

For to solve it, I created a different behavior in for `y` position in textSyle function and in `yP` when angle of rotation is different to zero. I tested it using `verticalAlign`: `top`, `middle` and `bottom`.

### Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### Checklist

- [ ] I have documented all new methods.
- [ ] I have written tests for all new methods/functionality.
- [ ] I have written examples for all new methods/functionality.

### CODE REVIEW

**Comment by cnavarreteliz** [comment]
My test code:

```    
const data = [
      {
        "angle": 0,
        "x": 50,
        "y": 100
      },
      {
        "angle": 45,
        "x": 250,
        "y": 100
      },
      {
        "angle": 90,
        "x": 450,
        "y": 100
      },
      {
        "angle": 135,
        "x": 650,
        "y": 100
      },
      {
        "angle": 180,
        "x": 850,
        "y": 100
      }
    ];



    new d3plus.Rect()
      .data(data)
      .rotate(d => d.angle)
      .width(50)
      .height(50)
      .x(d => d.x)
      .y(d => d.y)
      .fill("red")
      .strokeWidth(1)
      .label("....Test Label")
      .labelBounds({
        "x": 10,
        "y": -25,
        "width": 300,
        "height": 50
      })
      .labelConfig({
        padding: 0,
        strokeWidth: 2,
        textAnchor: "start",
        fontColor: "black",
        fontSize: 12, 
        verticalAlign: "middle" // Change between your options
      })
      .render();
```

**Review by davelandry — CHANGES_REQUESTED** [review]
@cnavarreteliz my tests in `d3plus-text` are not running. Looks like a problem with `verticalAlign`. Try using this example code inside of `d3plus-text` directly (instead of through `d3plus-shape`):

```html
<!doctype html>
<html>

<head>

  <meta charset="utf-8">
  <script src="../build/d3plus-text.full.js"></script>

  <style>

  body {
    margin: 0;
  }

  .box {
    border: 1px solid red;
    display: block;
    height: 30px;
    left: 100px;
    position: absolute;
    transform-origin: 0% 50%;
    width: 100px;
  }

  #box-1 {
    top: 0;
    transform: rotate(0deg);
  }

  #box-2 {
    top: 100px;
    transform: rotate(45deg);
  }

  #box-3 {
    top: 200px;
    transform: rotate(90deg);
  }

  #box-4 {
    top: 300px;
    transform: rotate(135deg);
  }

  #box-5 {
    top: 400px;
    transform: rotate(180deg);
  }

  </style>

</head>

<body>
  <div id="box-1" class="box"></div>
  <div id="box-2" class="box"></div>
  <div id="box-3" class="box"></div>
  <div id="box-4" class="box"></div>
  <div id="box-5" class="box"></div>
</body>

<script>

  var data = [{r: 0}, {r: 45}, {r: 90}, {r: 135}, {r: 180}];

  var text = new d3plus.TextBox()
    .data(data)
    .text("My Label")
    .height(30)
    .width(100)
    .verticalAlign("middle")
    .textAnchor("start")
    .x(100)
    .y((d, i) => i * 100)
    .rotate(d => d.r)
    .rotateAnchor([0, 15])
    .render();

</script>

</html>
```

Fiddle with the released version here: http://jsfiddle.net/8zcLndey/8/

File: src/TextBox.js [hunk 1]
```diff
@@ -270,7 +272,9 @@ export default class TextBox extends BaseClass {
             .attr("font-weight", d.fW)
             .style("font-weight", d.fW)
             .attr("x", `${d.tA === "middle" ? d.w / 2 : rtl ? d.tA === "start" ? d.w : 0 : d.tA === "end" ? d.w : 0}px`)
-            .attr("y", (t, i) => `${(i + 1) * d.lH - (d.lH - d.fS)}px`);
+            .attr("y", (t, i) => d.r === 0 || d.vA === "top" ? `${(i + 1) * d.lH - (d.lH - d.fS)}px` : 
+              d.vA === "middle" ? `${(d.h + d.fS) / 2 + (d.fS - d.lH)}px` : `${d.h - 2 * (d.lH - d.fS)}px`);
+
```
Comment (davelandry) [inline src/TextBox.js]: This logic breaks for multi-line text, try setting `.text("My Label and a second line")` in the last example I posted.

You need to take the `i` into account, which is the current line the text is on. This should hopefully also simplify this logic.

**Review by davelandry — CHANGES_REQUESTED** [review]

**Comment by davelandry** [comment]
@cnavarreteliz I've just released this fix with d3plus-text v0.9.33. Please test it in d3plus-shape, and the let me know if it solves the issues you were having in Radar!
